/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ArrayofOwnerContact;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-10-17T14:10:41.837Z[GMT]")
@Api(value = "PetOwnerContact", description = "the PetOwnerContact API")
public interface PetOwnerContactApi {

    @ApiOperation(value = "Returns contact details of pet owners within 5 mile radius.", nickname = "getLocationHistoryByPetNameOwnerName", notes = "Returns contact details of pet owners within 5 mile radius.", response = ArrayofOwnerContact.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "search results matching criteria", response = ArrayofOwnerContact.class),
        @ApiResponse(code = 400, message = "Pet Location History not found") })
    @RequestMapping(value = "/PetOwnerContact/{petName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ArrayofOwnerContact> getLocationHistoryByPetNameOwnerName(@ApiParam(value = "pass pet name for searching the location of Pets. ",required=true) @PathVariable("petName") String petName
);

}

